# dev
build_dev:
	docker-compose -f .\docker\docker-compose.dev.yml build --no-cache
up_dev:
	docker-compose -f .\docker\docker-compose.dev.yml up

#prod
build:
	docker-compose -f .\docker\docker-compose.yml build --no-cache
up:
	docker-compose -f .\docker\docker-compose.yml up
